name: Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deploy_condition:
        required: true
        type: boolean


jobs:
  deploy:
    if: ${{ inputs.deploy_condition }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
      - name: Simulate Deployment
        run: echo "Deploying to ${{ inputs.environment }} Environment"



  create-tag-after-prod:
    name: 'Create Tag After Prod'
    needs: deploy
    runs-on: ubuntu-latest
    if: needs.deploy.outputs.is_prod == 'true' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Download version file
        uses: actions/download-artifact@v4.1.4
        with:
          name: version
          path: /tmp
      
      - name: Read version from file
        id: read_version
        run: echo "VERSION=$(cat /tmp/version.txt)" >> $GITHUB_ENV
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Create and push tag based on GitVersion
        run: |
          VERSION=${{ env.VERSION }}
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
