name: Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deploy_condition:
        required: true
        type: boolean


jobs:
  deploy:
    if: ${{ inputs.deploy_condition }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Download version file
        uses: actions/download-artifact@v4.1.4
        with:
          name: version
          path: /tmp
      
      - name: Read version from file
        id: read_version
        run: echo "VERSION=$(cat /tmp/version.txt)" >> $GITHUB_ENV
        
      - name: Simulate Deployment
        run: echo "Deploying to ${{ inputs.environment }} Environment"


      - name: Create and push tag if prod and main branch
        if: ${{ inputs.environment == 'prod' && github.ref == 'refs/heads/main' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "VERSION=$(cat /tmp/version.txt)" >> $GITHUB_ENV
          VERSION=${{ env.VERSION }}
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v4.1.1
        with:
          path: /tmp


