name: Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deploy_condition:
        required: true
        type: boolean

jobs:
  deploy:
    if: ${{ inputs.deploy_condition }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Download version file
        uses: actions/download-artifact@v4.1.4
        with:
          name: version
          path: /tmp
      
      - name: Simulate Deployment
        run: echo "Deploying to ${{ inputs.environment }} Environment"

      - name: Setup Git and create tag if prod and main branch
        if: ${{ inputs.environment == 'prod' && github.ref == 'refs/heads/main' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          VERSION=$(cat /tmp/version.txt)
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
