name: Docker Image Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      dockerfile-path:
        required: false
        default: './Dockerfile'
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Download version file
        uses: actions/download-artifact@v2
        with:
          name: version
          path: /tmp
          
      - name: Set Docker tag
        id: set_tag
        run: echo "::set-output name=tag::$(cat /tmp/version.txt)"
        
      - name: Set Docker tagdsfs
        run: echo ${{ steps.set_tag.outputs.tag }}


      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: published-app
          path: ./publish
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Kaniko builder
        uses: aevea/action-kaniko@v0.11.0
        with:
          path: ${{ inputs.docker-context }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: szirmaibence98/testimage:0.1.0
#          ${{ inputs.image-name }}:${{ steps.set_tag.outputs.tag }}
          build_file: ${{ inputs.dockerfile-path }}
