name: Docker Image Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      dockerfile-path:
        required: false
        default: './Dockerfile'
        type: string
      release:
        description: 'Skip workflow if set to true for releases'
        required: false
        type: boolean
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker-build:
    if: ${{ github.ref == 'refs/heads/main' || (startsWith(github.ref, 'refs/heads/feature/') && github.event.inputs.feature == 'true') || startsWith(github.ref, 'refs/heads/hotfix/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Download version file
        uses: actions/download-artifact@v4.1.4
        with:
          name: version
          path: /tmp
          

      - name: Set Docker Tag
        run: |
          GITVERSION=$(cat /tmp/version.txt)
          # Always set appVersion to the GitVersion
          echo "DOCKER_TAG=$GITVERSION" >> $GITHUB_ENV
          
          # Check if the GitHub Action was triggered by a tag
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Extract the tag name by removing the 'refs/tags/' prefix
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "DOCKER_TAG=$TAG_NAME" >> $GITHUB_ENV
          else
            # Use a default version for non-tagged commits
            echo "chartVersion=0.0.1" >> $GITHUB_ENV
          fi



      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: published-app
          path: ./publish
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ inputs.image-name }}:${{ env.DOCKER_TAG }}
