name: Docker Image Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      dockerfile-path:
        required: false
        default: './Dockerfile'
        type: string
      version:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.dockerfile-path }} # Adjust as needed
          push: true
          tags: ${{ inputs.image-name }}:${{ inputs.version }}

