name: Docker Build and Push

on:
  workflow_call:
    inputs:
      image-names:
        description: 'JSON array of image names, contexts, and Dockerfile paths'
        required: true
        type: string
      release:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true



jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{fromJson(inputs.image-names)}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker-context }}
          file: ${{ matrix.docker-file }} # Use the specified Dockerfile
          push: true
          tags: ${{ matrix.image-name }}

