name: Docker Image Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      dockerfile-path:
        required: false
        default: './Dockerfile'
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Download version file
        uses: actions/download-artifact@v2
        with:
          name: version
          path: /tmp
          
#      - name: Set Docker tag
#        id: set_tag
#        run: echo "::set-output name=tag::$(cat /tmp/version.txt)"
        
#      - name: Set Docker tag
#        id: set_tag
#        run: |
#          VERSION=$(cat /tmp/version.txt)
#          CLEAN_VERSION=${VERSION/+/-} # Replace + with -
#          echo "::set-output name=tag::${CLEAN_VERSION}"

      - name: Set Docker tag with Branch Name
        id: set_tag
        run: |
          # Read the version from the file
          VERSION=$(cat /tmp/version.txt)
          # Replace + with - in version
          CLEAN_VERSION=${VERSION/+/-}
          # Extract current branch name using Git and sanitize it by replacing disallowed characters with -
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | sed 's/[^a-zA-Z0-9._-]/-/g')
          # Combine the cleaned version and sanitized branch name
          TAG="${CLEAN_VERSION}-${BRANCH_NAME}"
          echo "::set-output name=tag::${TAG}"

          
      - name: Set Docker tagdsfs
        run: echo ${{ steps.set_tag.outputs.tag }}


      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: published-app
          path: ./publish
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}




      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ inputs.image-name }}:${{ steps.set_tag.outputs.tag }}
