name: .NET Build and Test

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      project-paths:
        required: true
        type: string
      release:
        required: false
        type: boolean
        default: false


jobs:
  dotnet:
    runs-on: ubuntu-latest
    if: ${{ inputs.release == false }}
    strategy:
      matrix:
        project-path: ${{ fromJson(inputs.project-paths) }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.project-path }}

    - name: Build
      run: dotnet build ${{ matrix.project-path }} --no-restore -c Release

    - name: Test
      run: dotnet test ${{ matrix.project-path }} --no-build -c Release --verbosity normal

    - name: Prepare Artifact Name and Path
      id: prep
      run: |
        # Extracts the base name of the .csproj file, e.g., "dotnet" from "src/app1/dotnet.csproj"
        BASE_NAME=$(basename ${{ matrix.project-path }} .csproj)
        
        # Replaces any characters not allowed in artifact names or paths as needed
        ARTIFACT_NAME=${BASE_NAME//[^a-zA-Z0-9_]/_}
        
        # Construct the publish path using the artifact name
        PUBLISH_PATH="${{ github.workspace }}/publish/${ARTIFACT_NAME}"
        
        echo "Prepared artifact name: $ARTIFACT_NAME"
        echo "::set-output name=artifact_name::$ARTIFACT_NAME"
        
        echo "Publish path: $PUBLISH_PATH"
        echo "::set-output name=publish_path::$PUBLISH_PATH"
        
        # Ensure the publish path directory exists
        mkdir -p $PUBLISH_PATH


    - name: Publish
      run: dotnet publish ${{ matrix.project-path }} -c Release -o ${{ steps.prep.outputs.publish_path }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: ${{ steps.prep.outputs.artifact_name }}
        path: ${{ steps.prep.outputs.publish_path }}


