name: .NET Build and Test

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      project-paths:
        required: true
        type: string
      release:
        required: false
        type: boolean
        default: false
    secrets:
      pass:

jobs:
  dotnet:
    runs-on: ubuntu-latest
    if: ${{ inputs.release == false }}
    strategy:
      matrix:
        project-path: ${{ fromJson(inputs.project-paths) }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.project-path }}

    - name: Build
      run: dotnet build ${{ matrix.project-path }} --no-restore -c Release

    - name: Test
      run: dotnet test ${{ matrix.project-path }} --no-build -c Release --verbosity normal

    - name: Publish
      run: dotnet publish ${{ matrix.project-path }} -c Release -o ../publish/${{ matrix.project-path | replace('/','_') | replace('.csproj','') }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: published-app-${{ matrix.project-path | replace('/','_') | replace('.csproj','') }}
        path: ./publish/${{ matrix.project-path | replace('/','_') | replace('.csproj','') }}
