name: .NET

on:
  workflow_call: # This makes the workflow reusable
    inputs:
      dotnet-version:
        required: true
        type: string
      working-directory:
        required: false
        default: 'src' # Set default working directory to src
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ inputs.working-directory }}

    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: ${{ inputs.working-directory }}

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
      working-directory: ${{ inputs.working-directory }}
