
on:
  workflow_call: # This makes the workflow reusable
    inputs:
      dotnet-version:
        required: true
        type: string
      working-directory:
        required: false
        default: 'src' # Set default working directory to src
        type: string

jobs:

  docker-build:
    runs-on: ubuntu-latest
    container:
      image: docker://bitnami/kaniko:1.20.1-debian-12-r3
      options: --entrypoint "/bin/sh"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
      options: --user root
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Restore dependencies
        run: dotnet restore ./${{ inputs.working-directory }}/*.csproj

      - name: Build
        run: dotnet build ./${{ inputs.working-directory }}/*.csproj --configuration Release

      - name: Test
        run: dotnet test ./${{ inputs.working-directory }}/*.csproj --configuration Release
        

      - name: env
        run: env

      - name: Publish
        run: dotnet publish -c Release -o ./publish ./${{ inputs.working-directory }}/*.csproj 
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: ./publish

