name: .NET

on:
  workflow_call: # This makes the workflow reusable
    inputs:
      dotnet-version:
        required: true
        type: string
      working-directory:
        required: false
        default: 'src' # Set default working directory to src
        type: string

        
jobs:
  dotnet:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ inputs.working-directory }}

    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: ${{ inputs.working-directory }}

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
      working-directory: ${{ inputs.working-directory }}

    - name: Publish
      run: dotnet publish -c Release -o ../publish
      working-directory: ${{ inputs.working-directory }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: published-app
        path: ./publish

