name: Gitleaks


on:
  workflow_call:

jobs:

  gitleaks:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetches the complete commit history

      - name: Setup Gitleaks
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Save Gitleaks Results
        if: ${{ always() }}  # Always execute even if previous steps fail
        run: |
          mv results.sarif gitleaks-results-$(date +"%Y%m%d-%H%M%S").sarif
          echo "✅ Gitleaks scan completed"

  
      - name: Summarize Gitleaks Findings
        if: ${{ always() }}
        run: |
          sudo apt-get install jq -y
          SARIF_FILE=$(ls gitleaks-results-*.sarif)
          if [ ! -f "$SARIF_FILE" ]; then
            echo "Gitleaks SARIF file not found. ❌" >> $GITHUB_STEP_SUMMARY
          else
            LEAKS=$(jq '.runs[0].results | if length == 0 then "No leaks found." else map(.ruleId + ": " + .message.text) | .[] end' $SARIF_FILE)
            if [ "$LEAKS" == "No leaks found." ]; then
              echo "$LEAKS" >> $GITHUB_STEP_SUMMARY
            else
              echo "Leaks found:" >> $GITHUB_STEP_SUMMARY
              echo "$LEAKS" | sed 's/^/ - /' >> $GITHUB_STEP_SUMMARY
            fi
          fi



