

  gitversion:
    name: 'Determine Version'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.determine_version.outputs.MajorMinorPatch }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'     
          preferLatestVersion: true

      - name: Determine Version
        id: determine_version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
