name: GitVersion

on:
  workflow_call:
    outputs:
      version:
        description: "The calculated version"
        value: ${{ jobs.gitversion.outputs.version }}

jobs:
  gitversion:
    name: 'Determine Version'
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.determine_version.outputs.FullSemVer }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          preferLatestVersion: true
          
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: 'GitVersion.yml'

      - name: Display GitVersion FullSemVer
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}"

    
      - name: Set Output Version
        run: echo "version=${{ steps.gitversion.outputs.semVer }}" >> $GITHUB_ENV
        
      - name: Save version to file
        run: echo "${{ steps.gitversion.outputs.FullSemVer }}" > /tmp/version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: /tmp/version.txt

