name: GitVersion

on:
  workflow_call:
    outputs:
      version:
        description: "The calculated version"
        value: ${{ jobs.gitversion.outputs.version }}

jobs:
  gitversion:
    name: 'Determine Version'
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.determine_version.outputs.version }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          preferLatestVersion: true

      - name: Determine Version
        id: determine_version
        run: |
          # Run GitVersion command and capture the output
          version=$(gitversion)
          
          # Extract major, minor, and patch components from the version string
          major=$(echo $version | jq -r '.Major')
          minor=$(echo $version | jq -r '.Minor')
          patch=$(echo $version | jq -r '.Patch')
          
          # Concatenate major, minor, and patch components to form MajorMinorPatch version
          major_minor_patch="${major}.${minor}.${patch}"
          
          # Set the output
          echo "::set-output name=version::${major_minor_patch}"
