name: GitVersion

on:
  workflow_call:
    outputs:
      version:
        description: "The calculated version"
        value: ${{ jobs.gitversion.outputs.version }}

jobs:
  gitversion:
    name: 'Determine Version'
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.set_tag.outputs.tag }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          preferLatestVersion: true
          
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: 'GitVersion.yml'

      - name: Set Docker tag with Branch Name
        id: set_tag
        run: |
          # Read the version from GitVersion output
          VERSION="${{ steps.gitversion.outputs.semVer }}"
          # Replace + with - in version
          CLEAN_VERSION=${VERSION//+/-}
          # Extract current branch name using Git and sanitize it by replacing disallowed characters with -
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | sed 's/[^a-zA-Z0-9._-]/-/g')
          # Combine the cleaned version and sanitized branch name
          TAG="${CLEAN_VERSION}-${BRANCH_NAME}"
          echo "FullSemVer with Branch: $TAG"
          echo "::set-output name=tag::${TAG}"
        
      - name: Save version to file
        run: echo "${{ steps.set_tag.outputs.tag }}" > /tmp/version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: version
          path: /tmp/version.txt
