name: Package and Push Helm Chart to ACR


on:
  workflow_call:
    inputs:
      release:
        description: 'Skip workflow if set to true for releases'
        required: false
        default: 'false'
        type: boolean  
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

jobs:
  package-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Helm tool installer
        uses: Azure/setup-helm@v4
        with:
          version: latest

          

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | helm registry login szirmaibence98.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Package Helm chart
        run: helm package charts/mychart --destination .deploy

      - name: Push Helm chart to ACR
        run: |
          CHART_VERSION=$(helm show chart .deploy/mychart-*.tgz | grep 'version:' | cut -d ' ' -f 2)
          helm push .deploy/mychart-${CHART_VERSION}.tgz oci://szirmaibence98.azurecr.io/mychart

      # Optional: Add steps to verify the push, cleanup, etc.
