name: Package and Push Helm Chart to ACR


on:
  workflow_call:
    inputs:
      release:
        description: 'Skip workflow if set to true for releases'
        required: false
        type: boolean  
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

jobs:
  package-and-push:
    if: ${{ inputs.release == false }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download version file
        uses: actions/download-artifact@v4.1.4
        with:
          name: version
          path: /tmp
      
      - name: Set chartVersion and appVersion
        run: |
          GITVERSION=$(cat /tmp/version.txt)
          # Always set appVersion to the GitVersion
          echo "appVersion=$GITVERSION" >> $GITHUB_ENV
          
          # Check if the GitHub Action was triggered by a tag
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Extract the tag name by removing the 'refs/tags/' prefix
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "chartVersion=$TAG_NAME" >> $GITHUB_ENV
          else
            # Use a default version for non-tagged commits
            echo "chartVersion=0.0.1" >> $GITHUB_ENV
          fi

          
      - name: Helm tool installer
        uses: Azure/setup-helm@v4
        with:
          version: latest

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | helm registry login szirmaibence98.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin
        
      - name: Package Helm chart
        run: helm package charts/mychart -d .deploy --version ${{ env.chartVersion }} --app-version ${{ env.appVersion }}


  
      - name: Push Helm chart to ACR
        run: |
          CHART_VERSION=${{ env.chartVersion }}
          echo "Using chart version: $CHART_VERSION"
          helm push .deploy/mychart-${CHART_VERSION}.tgz oci://szirmaibence98.azurecr.io/mychart
