
name: Terraform Apply
on: workflow_call

jobs:

  deployment_test:
    name: 'Terraform Apply Test'
    needs: terraform_plan
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print ENV
        run: env

      - name: Print Environment Name
        run: echo "Environment Name is ${{ job.environment.name }}"