name: Terraform Plan
on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string

jobs:
  terraform-plan:
    name: 'Terraform Apply Test'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment_name }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Print ENV
        run: env
        
      - name: Print Environment Name
        run: echo "Environment Name is ${{ job.environment.name }}"
