name: Hello World Workflow
on: workflow_call

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World from Workflow 1!"

  terraform-plan:
    name: 'Terraform Apply Test'
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print ENV
        run: env
      - name: Print Environment Name
        run: echo "Environment Name is ${{ job.environment.name }}"
