name: Terraform
on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      arm_client_id:
        required: true
        type: string
      arm_client_secret:
        required: true
        type: string
      arm_subscription_id:
        required: true
        type: string
      arm_tenant_id:
        required: true
        type: string
      arm_access_key:
        required: true
        type: string

env:
  ARM_CLIENT_ID: ${{ inputs.arm_client_id }}
  ARM_CLIENT_SECRET: ${{ inputs.arm_client_secret }}
  ARM_SUBSCRIPTION_ID: ${{ inputs.arm_subscription_id }}
  ARM_TENANT_ID: ${{ inputs.arm_tenant_id }}
  ARM_ACCESS_KEY: ${{ inputs.arm_access_key }}
        
jobs:
  terraform-plan:
    name: 'Terraform Apply Test'
    runs-on: ubuntu-latest
    
#    environment: 
#      name: ${{ inputs.environment_name }}

      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -backend-config="key=${{ inputs.environment_name }}.terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="${{ inputs.environment_name }}.tfvars" -out="${{ inputs.environment_name }}.tfplan"

      - name: Archive Terraform Plan
        uses: actions/upload-artifact@v4.3.1
        with:
          name: terraform-plan
          path: ${{ inputs.environment_name }}.tfplan
